/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 5.1.61-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `card_info` (
	`seq` int (11),
	`cardname` varchar (765),
	`cardlevel` varchar (75),
	`cardtype` varchar (75),
	`cardrace` varchar (75),
	`cardactpower` varchar (75),
	`cardactive1` varchar (765),
	`cardactive1_waiting` varchar (15),
	`cardactive2` varchar (765),
	`cardactive2_waiting` varchar (15),
	`cardpassive1` varchar (765),
	`cardpassive2` varchar (765),
	`maineffect` varchar (765),
	`cardimage` varchar (765)
); 
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('2','인페르나','SSS','만능','악마','2.91','공간파괴','8','막강의구슬','8','약화','파멸','공격력 4.83%,공속 2.07%','인페르나.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('3','카자미르','SSS','전략','인간','3.53','낙뢰','7','비전격류','10','뇌전의힘','충격전이','스속 8.03%,방어 8.48%','카자미르.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('4','베아트리체','SSS','전략','악마','3.61','영원한고통','10','어둠의비전','10','죽음의그림자','수면가루','스속 8.03%, 공속 2.07%','베아트리체.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('5','베르실','SSS','방어','드래곤','2.56','화염의숨결','7','도발','8','응보','소생의빛','방어 19.79%,공속 2.07','베르실.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('6','그렌가르','SSS','공격','요정','2.33','영혼거두기','6','검은화살','6','원천봉쇄','절망','공속 4.83%, 공격력 2.07','그렌가르.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('7','피오라','SSS','공격','인간','2.33','단검투척','6','광포한질주','6','암살자의혼','파멸','공속 4.83, 공격력 2.07','피오라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('8','배너후드','SSS','만능','인간','2.86','흑월참','8','흙바람공격','8','살기','갑옷파괴','공격력 4.83%,방어 8.48%','배너후드.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('9','죽음의마녀에스텔','SSS','전략','인간','3.75','죽음의표식','10','어둠의비전','10','약점파악','죽음의예언','스속 11.46%','죽음의마녀에스텔.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('10','신성나비요정','SS','전략','요정','3.66','파멸의연기','10','탈진가루','10','추격','정기흡수','스속 6.69%, 최대생명력 3.26%','신성나비요정.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('11','네툴리아','SS','만능','요정','2.91','파멸의안개','8','자연의가르침','8','정기흡수','치유의축복','공격력 4.03%, 공속 1.73%','네툴리아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('12','덴드로','SS','만능','요정','2.86','파멸의안개','8','영혼의절규','8','시체폭발','추격','공격력 4.03%, 방어력 7.07%','덴드로.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('13','서펜트로','SS','공격','인간','2.24','폭발화살','6','치명적인관통','6','연계','연격','공속 4.03%, 스속 2.87%','서펜트로.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('14','플렌티아','SS','지원','요정','3.41','부활의마법진','30','자연의빛','9','생명의은총','회복차단','최대생명력 7.6%, 스속 2.87%','플렌티아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('15','쿠플린','SS','만능','몬스터','3.13','초열지옥','8','혼돈의파동','8','분노의힘','인내','공격력 5.75%','쿠플린.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('16','바위골렘','SS','방어','몬스터','2.50','광포한내려찍기','7','도발','8','위협의외침','강인한의지','방어력 23.55%','바위골렘.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('17','라트리스','SS','공격','요정','2.08','별의조각','6','절개','6','매의눈','신속','공속 5.75%','라트리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('18','웰드레인져','SS','만능','요정','2.91','유성강림','8','자연의가르침','8','혼돈','심장가격','공격력 4.03%, 공속 1.73%','웰드레인져.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('19','레지나루노','SSS','지원','인간','3.33','천상의보호막','9','온유한 정화','10','','','최대생명력 13.02%','레지나루노.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('20','이그니아','SSS','전략','인간','3.61','불새소환','10','불벼락','7','','','스속 8.03%,공속 2.07%','이그니아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('21','용병왕마르칸','SSS','공격','인간','2.01','굉포한일격','6','절개','6','','','','용병왕마르칸.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('22','이그니스','SSS','전략','인간','3.61','화염작렬','7','불벼락','7','','','스속 8.03%, 공속 2.07%','이그니스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('23','드라마담','SSS','공격','인간','2.33','혈룡의분노','6','정신붕괴','6','','','공속 4.83%, 공격력 2.07%','드라마담.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('24','푸른달의마녀','SSS','공격','인간','2.33','초성폭발','6','마력붕괴','6','','','공속 4.83%, 공격력 2.07%','푸른달의마녀.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('25','붉은달의마녀','SSS','공격','인간','2.24','화염폭발','6','피의갈망','6','','','공속 4.83%,스속 3.44%','붉은달의마녀.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('26','브로큰티어여사제','SSS','전략','인간','3.66','어둠의소용돌이','10','정화의기운','10','','','스속 8.03%,최대생명력 3.91%','브로큰티어여사제.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('27','잭스펜서','SSS','전략','인간','3.80','영혼잠식','6','피의향연','7','','','','잭스펜서.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('28','시어러','SSS','공격','인간','2.24','염화','6','불꽃의칼날','6','','','','시어러.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('29','불의여사제','SSS','전략','인간','3.66','별빛섬광','10','화염구','8','','','스속 8.03%, 최대생명력 3.91%','불의여사제.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('30','지옥표범','SSS','방어','몬스터','2.56','연옥의불길','7','분노의포효','7','','','방어력 19.79%,공속 2.07%','지옥표범.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('31','대마법사냥코','SSS','전략','몬스터','3.66','유성폭격','8','일점사','10','','','스속 8.03%, 최대생명력 3.91%','대마법사냥코.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('32','캘시퍼의눈','SSS','전략','몬스터','3.53','업화','7','화염구','8','','','','캘시퍼의눈.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('33','뿔오우거','SSS','공격','몬스터','2.01','광포한일격','6','통한의일격','6','','','공속 4.83%, 방어력 8.48%','뿔오우거.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('34','제롬올렌더','SSS+','만능','인간','2.86','광폭찍기','8','화염베기','8','','','공격력 5.64%, 방어력 9.9%','제롬올렌더.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('35','챠바나','SSS+','방어','몬스터','2.50','영혼흡수','16','챠바나의수호','10','','','방어력 32.97%','챠바나.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('36','레티르','SSS+','공격','요정','2.08','비전낙하','6','에너지폭류','6','','','공속 8.05%','레티르.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('37','나르샤','SSS+','전략','튜톤','3.61','죽음의축제','5.5','암흑의소용돌이','7','','','공속 8.05%','나르샤.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('38','세리엘','SSS+','지원','천사','3.49','심판의일격','9','신성정화','7','','','최대생명력 10.64%, 공격력 2.42%','');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('39','단테','SSS+','공격','악마','2.08','마계의인장','7','연속가르기','7','','','공속 8.05%','단테.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('40','모르간','SSS','공격','악마','2.08','격렬한고통','6','혼돈의공포','6','','','공속 6.9%','모르간.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('41','아홉번째성기사','SSS','방어','인간','2.56','만월참','7','분쇄의일격','7','','','방어력 19.79%, 공속 2.07%','아홉번째성기사.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('42','엘토르네오','SSS','만능','천사','3.13','성야유성권','8','성천강권','6','','','공격력 7.47%','엘토르네오.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('43','카르가스','SSS','만능','인간','3.13','신성한분노','6','냉기탄환','8','','','공격력 6.9%','카르가스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('44','트리아크','SSS','전략','드래곤','3.61','낙뢰','7','냉기격류','7','','','스속 8.03%, 공속 2.07%','트리아크.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('45','발라크','SSS','전략','드래곤','3.61','어둠의소용돌이','10','파멸의파동','7','','','스속 8.03%, 공속 2.07%','발라크.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('46','쿠아크란','SSS','만능','드래곤','2.91','영혼강탈','6','혼돈의파동','8','','','','쿠아크란.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('47','에니드','SSS','만능','튜톤','3.06','뇌우','8','그림자베기','8','','','공격력 4.83%, 스속 3.44%','에니드.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('48','공황의근위병','SSS','공격','튜톤','2.01','비전폭격','6','진공칼날','6','','','공속 4.83%, 방어력 8.48%','공황의근위병.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('49','무칼리','SSS','공격','천사','2.01','검은질풍','6','진공칼날','6','','','공속 4.83%, 방어력 8.48%','무칼리.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('50','시그룬','SSS','전략','천사','3.53','서릿바람','7','탈진가루','10','','','스속 8.03%, 방어력 8.48%','시그룬.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('51','롤랑','SSS','전략','인간','3.66','대폭발','10','빛의일격','10','','','스속 8.03%, 최대생명력 3.91%','롤랑.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('52','데모니카라','SSS','전략','악마','3.66','죽음의표식','10','암흑의날개','10','','','','데모니카라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('53','볼칸','SSS','만능','드래곤','3.13','독의숨결','8','드래곤의포효','8','','','공격력 6.9%','볼칸.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('54','벨리스트라','SSS','전략','악마','3.61','영혼가르기','8','악마의갈퀴','10','','','공속 2.07%, 스속 8.03%','벨리스트라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('55','마야','SSS+','공격','인간','2.08','심판하는은빛칼날','6','어둠의장막','6','','','공속 8.05%','마야.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('56','이오니아','SSS+','지원','요정','3.49','여왕의축복','20','혹한의축제','20','','','최대생명력 10.64%, 공격력 2.42%','이오니아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('57','베나','SSS','공격','요정','2.24','폭발화살','6','검은화살','6','','','공속 4.83%, 스속 3.44%','베나.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('58','데미트리','SSS+','공격','튜톤','2.24','파멸과비탄의밤','10','피의윤회','9','','','공속 5.64%, 스속 4.02%','데미트리.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('59','블레스크','SSS','전략','튜톤','3.61','낙뢰','7','서리뇌전','9','','','스속 8.03%, 공속 2.07%','블레스크.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('60','발키르잔','SSS','공격','천사','2.01','신성한분노','6','달빛가르기','6','','','공속 4.83%, 방어력 8.48%','발키르잔.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('61','제피로스','SSS','만능','악마','3.06','열정의원혼','6','사신의전주곡','8','','','공격력 4.83%, 스속 3.44%','제피로스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('62','힐렌','SSS','전략','요정','3.80','혈룡소환','9','어둠의비전','10','','','스속 8.03%, 공격력 2.07%','힐렌.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('63','불드레이크','SSS','공격','드래곤','2.08','진홍의숨결','6','타오르는발톱','6','','','공속 6.9%','불드레이크.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('64','타타우르스','SSS','만능','몬스터','2.86','광폭찍기','8','검은일격','8','','','공격력 4.83%, 방어력 8.48%','타타우르스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('65','플레쉬몽거','SSS','방어','튜톤','2.70','악령의습격','7','분쇄의일격','7','','','방어력 19.79%, 스속 3.44%','플레쉬몽거.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('66','브리실다','SSS','전략','튜톤','3.80','죽음의손길','7','타락한영혼','10','','','스속 8.03%, 공격력 2.07%','브리실다.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('67','화염메두사','SSS','전략','몬스터','3.80','업화','7','매혹적인불덩이','6','','','스속 8.03%, 공격력 2.07%','화염메두사.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('68','헬레나','SSS','지원','인간','3.33','영혼방벽','6','매혹의향기','10','','','','헬레나.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('69','외로운발렌타인오우거','SS','방어','몬스터','2.50','고통의메아리','8','혼자서도충분하다','8','','','','외로운발렌타인오우거.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('70','파괴신의배우자','SSS','만능','악마','3.06','광기의돌풍','8','마력돌개바람','8','','','공격력 4.83%, 스속 3.44%','파괴신의배우자.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('71','로테만','SSS','방어','인간','2.5','서리강타','6','냉기의일격','6','','','','로테만.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('72','자카레','SSS','공격','인간','2.24','빛의포격','4','에너지파동','6','','','','자카레.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('73','그리피오스','SSS+','만능','몬스터','3.06','폭풍의날개짓','8','음속의파동','8','','','공격력 5.64%, 방어력 9.9%','그리피오스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('74','마키아','SSS','만능','요정','3.13','흑월참','8','반월베기','8','','','','마키아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('75','카벨','SSS+','공격','드래곤','2.33','화룡의분노','6','작열하는분노','6','','','공속 5.74%, 공격력 2.42%','카벨.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('76','그라시아','SSS+','만능','천사','3.0','신성징벌','8','악마정화','8','','','공격력 5.64%, 최대생명력 4.56%','그라시아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('77','안젤리카라','SSS','지원','천사','3.49','부활의마법진','30','광명의날개','9','','','','안젤리카라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('78','루시펠','SSS','만능','악마','3.06','공간파괴','8','칠흑의불길','8','','','','루시펠.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('79','불사의마녀','SSS','전략','인간','3.75','불새소환','10','화염구','8','','','','불사의마녀.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('80','튜톤대형골렘','SSS','방어','몬스터','2.56','광포한내려찍기','7','도발','8','','','','튜톤대형골렘.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('81','카샤스','SSS','공격','드래곤','2.08','타오르는업화','6','타오르는발톱','6','','','','카샤스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('82','펠렁','SSS','만능','드래곤','3.06','진홍의불길','8','영혼의절규','8','','','','펠렁.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('83','크림킨드','SSS','공격','드래곤','2.08','화룡의분노','6','타오르는발톱','6','','','','크림킨드.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('84','그랜드리전','SSS','방어','튜톤','2.50','광포한내려찍기','7','도발','8','','','','그랜드리전.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('85','무닌','SSS','공격','튜톤','2.24','영혼거두기','6','피의갈망','6','','','','무닌.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('86','캘시퍼','SSS','방어','악마','2.78','겁화','7','도발','8','','','','캘시퍼.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('87','헤브니움 버스터','SSS+','전략','몬스터','3.53','파멸의주먹','8','고출력 마력포','8','','','스속 9.37%, 방어력 9.89%','헤브니움 버스터.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('88','홀리버드','SSS+','지원','몬스터','3.41','광휘의기운','10','빛의파동','10','','','최대생명력 10.64%,스속 4.02%','홀리버드.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('89','승천의 룬 골렘','SSS','방어','몬스터','2.50','도발','8','마력파동','8','','','','승천의 룬 골렘.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('90','철혈의 카라크','SSS','공격','몬스터','2.01','무자비한 발톱','6','광포한 질주','6','','','공속 4.83%, 방어력 8.48%','철혈의 카라크.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('91','모그라투스','SSS','만능','몬스터','2.86','발구르기','8','부서지는대지','8','','','공격력 4.83%, 방어력 8.48%','모그라투스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('92','엘라시엔','SSS','지원','요정','3.33','자연의빛','9','정화의기운','10','','','','엘라시엔.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('93','셀바스테인','SSS+','지원','인간','3.33','안전한정화','12','구원의뇌전','10','','','최대생명력 15.19%','셀바스테인.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('94','네쉬르','SSS','공격','몬스터','2.08','침묵의파도','6','심연의노래','6','','','공속 6.9%','네쉬르.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('95','아르시엔','SSS','공격','요정','2.16','달빛가르기','6','신성한분노','6','','','','아르시엔.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('96','티리스','SSS','전략','요정','3.66','빛의심판','10','별빛섬광','10','','','','티리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('97','헤브니얼엘프감시자','SSS','공격','요정','2.33','연속베기','7','진공칼날','6','','','','헤브니얼엘프감시자.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('98','헤브니얼엘프순찰자','SSS','만능','요정','2.91','검은일격','8','영혼베기','6','','','','헤브니얼엘프순찰자.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('99','기브엘','SSS+','공격','천사','2.24','천상의검','6','빛의포효','6','','','공속 5.64%, 스속 4.02%','기브엘.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('100','비드온','SSS+','방어','몬스터','2.78','뿌리휘감기','8','가시갑옷','12','','','방어력 23.08%, 공격력 2.42%','비드온.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('101','그림자야수','SSS','공격','몬스터','2.33','악몽의그림자','6','영혼삼키기','6','','','','그림자야수.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('102','레퓨리아','SSS','전략','요정','3.66','자연의외침','8','어둠의소용돌이','10','','','','레퓨리아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('103','플레타','SSS','공격','요정','2.24','비전강타','6','어둠베기','6','','','','플레타.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('104','드라이어드','SSS','전략','요정','3.66','원혼의축제','7','정령의분노','10','','','','드라이어드.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('105','레가드리스','SSS+','전략','튜톤','3.75','악몽의검','7','죽음의숨결','10','','','스속 13.37%','레가드리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('106','벨트로스','SSS+','전략','인간','3.75','맹렬한불길','10','심연의불꽃','8','','','스속 13.37%','벨트로스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('107','루아나프라','SSS+','전략','인간','3.66','달의가호','10','찬란한달빛','10','','','공속 8.05%','루아나프라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('108','알테가스','SSS+','전략','튜톤','3.75','죽음의대지','7','무한의갈증','10','','','스속 13.37%','알테가스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('109','공허의정령','SSS','만능','튜톤','2.91','고통의악령','8','검은영혼의절규','8','','','','공허의정령.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('110','길리언','SSS+','만능','악마','2.91','타오르는분노','8','어둠의창','8','','','공격력 5.64%, 공속 2.42%','길리언.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('111','검은날개주술사','SSS','만능','악마','3.06','지옥의가시','10','욕망의칼날','8','','','','검은날개주술사.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('112','칠흑날개추방자','SSS','공격','악마','2.08','검은질풍','6','푸른절개','6','','','','칠흑날개추방자.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('113','마리안느','SSS+','공격','악마','2.16','매혹의꿈','6','밤의기억','5','','','','마리안느.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('114','프랑켄소와즈','SSS','전략','튜톤','3.80','사탕받아줘','10','나의호박님','10','','','','프랑켄소와즈.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('115','미느엘','SSS+','만능','천사','3.00','새벽의빛','12','영원한승천','12','','','공격력 5.64%, 최대생명력 4.56%','미느엘.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('116','가르시엘라','SSS+','공격','천사','2.16','단죄의검','6','섬광난무','6','','','공속 5.64%, 최대생명력 4.56%','가르시엘라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('117','엑슬리온','SSS+','방어','천사','2.63','불멸의성역','10','붉은빛의가호','10','','','방어력 23.08%, 최대생명력 4.56%','엑슬리온.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('118','소니아','SSS','공격','천사','2.08','금빛화살','6','섬광폭우','6','','','','소니아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('119','승천의인도자','SSS','지원','천사','3.41','신의가호','9','천상의보호막','9','','','','승천의인도자.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('120','실피네스','SSS','지원','요정','3.33','폭풍의장벽','10','날카로운바람','10','','','최대생명력 14.13%','실피네스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('121','로제타','SSS+','지원','요정','3.41','꽃가루의향연','9','평온의씨앗','9','','','최대생명력 10.64%, 스속 4.02%','로제타.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('122','프레이즈','SSS+','전략','요정','3.61','설풍','10','혹한의파편','10','','','스속 9.36%, 공격력 2.42%','프레이즈.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('123','성탄절의로제타','SSS','전략','요정','3.61','거룩한밤의선물','10','어두운밤의불빛','10','','','','성탄절의로제타.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('124','성탄절의루디','SSS','전략','요정','3.61','고요한밤의눈보라','10','거룩한밤의선물','10','','','','성탄절의루디.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('125','헥스','SSS+','만능','악마','3.13','칠흑의칼날깃털','8','타천사의권능','8','','','공격력 8.05%','헥스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('126','카트리스','SSS+','전략','인간','3.80','고요한폭발','10','불꽃과희망의춤','10','','','스속 9.36%, 공격력 2.42%','카트리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('127','딜라이트','SSS+','만능','인간','2.86','오라캐논','8','챠크라필드','8','','','공격력 5.64%, 방어력 9.9%','딜라이트.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('128','페렐로롯시에','SSS','지원','요정','3.49','찬란한빛의가루','8','특제각성향','8','','','','페렐로롯시에.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('129','매혹의발렌타인엘프','SS','만능','요정','2.86','달콤한춤사위','8','초콜릿축제','6','','','','매혹의발렌타인엘프.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('130','달콤한캘시퍼의눈','SS','전략','몬스터','3.53','초코볼튕기기','8','나열받았어','8','','','','달콤한캘시퍼의눈.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('131','스카레스','SSS+','전략','드래곤','3.75','죽음의메아리','10','사신의안개','10','','','스속 13.37%','스카레스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('132','칼페리온','SSS+','전략','드래곤','3.80','멸망의숨결','10','단죄의불꽃','10','','','스속 9.36%,공격력 2.42%','칼페리온.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('133','헬카이트','SSS+','만능','드래곤','2.86','황혼유성','8','지옥의불길','8','','','공격력 5.64%,방어력 9.9%','헬카이트.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('134','히실리스','SSS+','전략','드래곤','3.61','백룡소환','7','연사','8','','','스속 9.36%, 공속 2.42%','히실리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('135','칼리','SSS+','전략','악마','3.80','흑마의발톱','10','붉은밤의악몽','10','','','스속 9.36%, 공격력 2.42%','칼리.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('136','메피스토','SSS+','전략','악마','3.75','흑의망령','10','사신의숨결','10','','','스속 13.37%','메피스토.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('137','리리스','SSS+','지원','악마','3.49','욕망의발현','8','유혹의사슬','8','','','최대생명력 10.64%, 공격력 2.42%','리리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('138','루미너스','SSS+','지원','요정','3.33','대정령의빛','9','대정령의분노','9','','','최대생명력 15.19%','루미너스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('139','엘카너스','SSS+','전략','요정','3.75','하늘의분노','10','타오르는갑옷','12','','','스속 13.37%','엘카너스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('140','이아나','SSS+','공격','튜톤','2.24','습격','7','급소도려내기','7','','','공속 5.64%,스속 4.02%','이아나.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('141','이프리타','SSS+','만능','튜톤','2.86','파멸의낙인','6','불타는괴수','8','','','공격력 5.64%, 방어력 9.9%','이프리타.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('142','알폰스','SSS+','공격','악마','2.24','흡혈각인','5','진혈이식','8','','','공속 8.05%','알폰스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('143','미호','SSS+','전략','몬스터','3.80','치명적인매혹','7','치명적인매력','12','','','','미호.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('144','베르딘','SSS+','공격','요정','2.33','신중한일격','10','화살폭격','7','','','','베르딘.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('145','마리아','SSS+','전략','천사','3.75','선물폭격','11','불타는선물','9','','','스속 13.37%','마리아.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('146','피닉스','SSS+','전략','몬스터','3.61','화염발톱','8','소각','10','','','스속 9.36%, 공속 2.42%','피닉스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('147','아이리스','SSS+','지원','요정','3.26','찬란한파동','9','찬란한보호','7','','','최대생명력 10.64%, 공속 2.42%','아이리스.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('148','아칸트','SSS+','방어','드래곤','2.56','굉음의포효','8','드래곤의결속','8','','','방어력 23.08%, 공속 2.42%','아칸트.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('149','듀크','SSS+','전략','튜톤','3.75','저주의안개','7','저주의일격','10','','','스속 13.37%','듀크.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('150','니프리드','SSS+','만능','튜톤','3.13','지친영혼에의표식','8','피흘리는영혼수확','10','','','공격력 8.05%','니프리드.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('151','아게르나','SSS+','방어','천사','2.50','칼날의춤','8','반격준비','11','','','방어력 32.97%','아게르나.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('152','산드라','SSS+','전략','인간','3.80','검은낙수','10','검은살수','10','','','스속 9.36%, 공격력 2.42%','산드라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('153','디할라','SSS+','만능','몬스터','2.86','시간돌풍','10','시간족쇄','13','','','공속 5.64%, 방어력 9.9%','디할라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('154','헤브니움가디언','SSS+','방어','몬스터','2.5','강성강화','10','고출력보호막','10','','','방어력 32.97%','헤브니움가디언.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('155','아크베이든','SSS+','전략','드래곤','3.61','절망의발톱','10','절망의화염','10','','','스속 9.36%, 공속 2.42%','아크베이든.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('156','벨라','SSS+','공격','요정','2.24','가시채찍','8','가시동굴포박','8','','','공속 5.64%, 스속 4.02%','벨라.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('157','밴시','SSS+','만능','튜톤','2.91','기습','8','상처찢기','10','','','공격력 5.64%, 공속 2.42%','밴시.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('158','파이톤','SSS+','공격','몬스터','2.08','포식자의도축','10','포식자의광분','12','','','공속 8.05%','파이톤.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('159','아스타로트','SSS+','만능','악마','3.06','지옥의염화','10','파멸의검','10','','','공격력 5.64%, 스속 4.02%','아스타로트.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('160','브린힐트','SSS+','만능','악마','3.13','화염가르기','10','벼락찍기','10','','','공속 8.05%','브린힐트.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('161','해골수집광','SSS','전략','튜톤','3.66','파멸의연기','10','망자의빛','10','','','스속 8.03%, 최대생명력 3.91%','해골수집광.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('162','퀸 엘리제','SSS+','지원','인간','3.49','얼음파편','10','서리폭풍','10','','','','퀸 엘리제.jpg');
insert into `card_info` (`seq`, `cardname`, `cardlevel`, `cardtype`, `cardrace`, `cardactpower`, `cardactive1`, `cardactive1_waiting`, `cardactive2`, `cardactive2_waiting`, `cardpassive1`, `cardpassive2`, `maineffect`, `cardimage`) values('163','아라크네','SSS+','만능','몬스터','3.00','끈적한거미줄','8','거미독','10','','','공격력 5.64%, 최대생명력 4.56%','아라크네.jpg');
